httpClient:
  timeout: 10s
  connectionTimeout: 10s

database:
  file: /tmp/mm/shows.db

torrents:
  watchDir: /tmp/mm/torrents/watch/
  qualities: [ "720p" ]
  parsers:
    scc:
      passKey: 3a06551fd736a161fdf8ed1ce7417c30
    hdbits:
      passKey: b19a20fd6e28810858711788fa7486f2

calendars:
  parsers:
    pogdesigns:
      passKey: d88adb70e7f4c8950f1d1643110d2099

files:
  watchDir: /tmp/mm/torrents/downloaded/
  destinationDir: /tmp/mm/tv shows/
